### ISSUE TITLE
Firewall discovery controle check issue

### ISSUE THREAD

**Issue by technl** [jebr/windows-deployment-tool#21]
Firewall discovery controle check wordt niet correct weergeven,, de gevens corresponderen uiteindelijk niet met de realtiteit.

**Comment by jebr** [comment]
Het probleem vind alleen plaats op een NL Windows systeem. De juiste Windows Firewall benaming is "Netwerk detecteren".

**Comment by jebr** [comment]
Fixed in versie 2.41
